#!/bin/sh
# Unpack the JWS distribution, possibly patch it, move components into place,
# then delete the rest
set -e
JWS_HOME=/opt/jws-5.7/tomcat
ADDED_DIR=/tmp/artifacts
GENERAL_ZIPS=$ADDED_DIR/jws-5.7.?-application-server.zip
PLATFORM_ZIPS=$ADDED_DIR/jws-5.7.?-application-server-RHEL?-$(uname -m).zip
mkdir -p -m0755 $JWS_HOME

# unzip distribution and apply any patches
for zip in $GENERAL_ZIPS; do
  unzip -o "$zip" -d /opt
done

# unzip platform specific zips and apply patches
for zip in $PLATFORM_ZIPS; do
  unzip -o "$zip" -d /opt
done

# tidy up
rm -rf $ADDED_DIR/jws-5.7.*
